name: Release

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make trimix zip
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/trimix.zip
          generate_release_notes: true
